version: '3.8'
services:
  oracle-db:
    image: wnameless/oracle-xe-11g
    container_name: oracle-db
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
      - "8080:8080"  # APEX (optional)
    networks:
      - product-network

  product-ws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-ws
    ports:
      - "9292:9292"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:XE
      SPRING_DATASOURCE_USERNAME: scott
      SPRING_DATASOURCE_PASSWORD: tiger
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.Oracle10gDialect
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
